# Generated by Django 4.2.2 on 2023-06-10 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicasImagen',
            fields=[
                ('id_caracteristica', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_instante', models.DateTimeField()),
                ('caracteristica1', models.CharField(max_length=100)),
                ('caracteristica2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsuariosHijos',
            fields=[
                ('id_usuario_hijo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('plan', models.CharField(choices=[('P', 'Premium')], default='P', max_length=1)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='UsuariosPadres',
            fields=[
                ('id_usuario_padre', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PadresHijos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_hijo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Imagenes.usuarioshijos')),
                ('usuario_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Imagenes.usuariospadres')),
            ],
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id_imagen', models.IntegerField(primary_key=True, serialize=False)),
                ('ruta_imagen', models.CharField(max_length=255)),
                ('caracteristica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Imagenes.caracteristicasimagen')),
            ],
        ),
        migrations.AddField(
            model_name='caracteristicasimagen',
            name='usuario_hijo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Imagenes.usuarioshijos'),
        ),
    ]
