# Generated by Django 4.2.2 on 2023-06-10 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Imagenes', '0003_remove_caracteristicasimagene_caracteristica1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaracteristicasImagene',
            new_name='CaracteristicasImagenes',
        ),
        migrations.RenameModel(
            old_name='Imagene',
            new_name='Imagenes',
        ),
        migrations.RenameModel(
            old_name='PadresHijo',
            new_name='PadresHijos',
        ),
        migrations.RenameModel(
            old_name='UsuariosHijo',
            new_name='UsuariosHijos',
        ),
        migrations.RenameModel(
            old_name='UsuariosPadre',
            new_name='UsuariosPadres',
        ),
    ]
